### ISSUE TITLE
Add Vlocity release notes to the bot

### ISSUE THREAD

**Issue by thvd** [SFXD/Release-Note-checker#1]
Would be great to be notified about Vlocity releases. The releases are listed here: https://docs-vhc.vlocinternal.com/vhc/packageinventory/package-inventory-CMT.html

**Comment by Windyo** [comment]
Hey, that bot is deprecated, but I'll add it to the event stream manager.
I should update this repo as well with the new functions I guess.
I'll add a todo and ping back when I'm done.

**Comment by Windyo** [comment]
Wait, those version numbers make no sense to me - what's the numbering format and logic ? Sorry, not really a Vlocity guru

**Comment by thvd** [comment]
Where is the repo for the new bot? 
The version scheme: The column "Package Version" is the official managed package version number. 
For example "900.408.9":
- 900: major version
- 408: minor version
- 9: patch version

Then there is the internal version scheme (column Internal version). For example "CME 230.3.1"
- 230: is the release, like (for example) Salesforce summer 2021.
- 3.1: is the patch version number

**Comment by Windyo** [comment]
Ain't no repo yet, the bot's a Huginn event stream.

Considering the above - if I parse the page and get
<html><body>


Summary | Package Version | Released | Download Link | Sandbox Link | Release Notes | Internal Version
-- | -- | -- | -- | -- | -- | --
CME 230.3.1.900.408.9 (Spring 2021 Patch Release) | 900.408.9 | Jul 8, 2021 | [Production Download] | [Sandbox Download] | For details, see the Patch Releases section in https://docs.vlocity.com/en/CME-230-Release-Overview.html | CME 230.3.1
CME 232.0.900.434 (Summer 2021 Release) | 900.434 | Jun 25, 2021 | [Production Download] | [Sandbox Download] | See the Help Center for release notes and supporting  documentation:  https://docs.vlocity.com/en/CME-232-Release-Overview.html | 232


</body>
</html>

Do you expect a notification to be sent because there's a new line, or should I disregard the update because 408 < 434 ?

**Comment by thvd** [comment]
I would say if there is a new row in the table, that's what's i interesting right? To be notified about a new release? 

It doesn't tell the release notes are updated, but in order to check that you have to login to the success portal. That's getting quite complicated i can imagine, so this would be a great start.

**Comment by Windyo** [comment]
> I would say if there is a new row in the table, that's what's i interesting right? To be notified about a new release?

I can justify both - I imagine that if you care about new releases, you don't care about patches, esp as patches seem to be frequent.

I think what I'll do is parse the version number, and do three notification streams - one for major, one for minor, one for patch.

**Comment by thvd** [comment]
Sounds good to me! The major version ( of the official package version number) will never be updated as far as i know. So i would just major + minor (combine both)

**Comment by Windyo** [comment]
Can you confirm what CME is ? Am I checking releases for all Vlocity or just a specific industry ?	Just so I know how I name stuff

**Comment by thvd** [comment]
Good one, CME is Communications and Media Entertainment. There are more indeed:
- Communications, Media & Entertainment, and Energy & Utilities Major Releases  (CME/CMT): https://docs-vhc.vlocinternal.com/vhc/packageinventory/package-inventory-CMT.html
- Insurance and Health Major Releases: https://docs-vhc.vlocinternal.com/vhc/packageinventory/package-inventory-insurance.html
- Government Major Releases: https://docs-vhc.vlocinternal.com/vhc/packageinventory/package-inventory-PS.html

**Comment by Windyo** [comment]
I was hoping I could get a full list by GET'in docs-vhc.vlocinternal.com/vhc/packageinventory/ but sadly it 401's.
I'll start by building a PoC for CMT and extend to whatever other URL I find.

I probably won't plug those to @SFXD_Bot on twitter because I can publish to specific event channels there, but I'll shove that to Discord with specific tags and publish a release endpoint that'll support RSS, that way you can subscribe to it out of Discord.

**Comment by Windyo** [comment]
Alright ehre's a quick PoC of what I could expose.
I'm not filtering by stream for this PoC, but the filter is the easy part.
LMK if taht works for your usecase. Reg Dsicord that one's easy as hell, I'll finish up in my free time tonight.
https://huginn.bessereau.eu/users/1/web_requests/37/sfxd-vlocity.json

**Comment by Windyo** [comment]
I'm an idiot who archived the repo before closing this. Oh well.

Anyway, unarchiged dso we can finish this up.
CMT now has three RSS endpoints:

https://huginn.bessereau.eu/users/1/web_requests/42/sfxd-vlocity.json
https://huginn.bessereau.eu/users/1/web_requests/41/sfxd-vlocity.json
https://huginn.bessereau.eu/users/1/web_requests/37/sfxd-vlocity.json

I'm prepping the Discord notifying roles as well.
Should eb done in like 30 minutes.

I'll set up the SFXD tiwtter bot to tweet on new Minor versions, not patch ones. I think taht'll be rare enough and valuable.

**Comment by Windyo** [comment]
![image](https://user-images.githubusercontent.com/17938171/126333070-68dc99e9-e855-4eea-a6a9-258ea28152aa.png)

**Comment by Windyo** [comment]
![image](https://user-images.githubusercontent.com/17938171/126333827-06d4b665-a3d3-42e0-8e95-8561067228af.png)

**Comment by Windyo** [comment]
KK, I think that covers it.I'll go over the other pages, they seem to parse the same.
We good on your side @thvd ?

**Comment by thvd** [comment]
What would be helpfull is to see the versionnumber in the notification? Is that possible? 
That package `package` node in the JSON

**Comment by Windyo** [comment]
done
![image](https://user-images.githubusercontent.com/17938171/126337710-05fb5c81-79c9-4e1f-a474-8787b2e65f64.png)

![image](https://user-images.githubusercontent.com/17938171/126337734-725b8b69-9561-4832-aff2-0b2545e4e063.png)

**Comment by thvd** [comment]
Thanks looks great!

**Comment by Windyo** [comment]
cool, will do other Vlocity links you sent, if you know of others LMK.

**Comment by Windyo** [comment]
Just in case, here's the Huginn definition file. 
https://huginn.bessereau.eu/scenarios/5/export.json
